stages:
  - build

variables:
  DOTNET_VERSION: "8.0"
  CONFIGURATION: "Release"

before_script:
  - echo "Setting up .NET environment"
  - dotnet --version

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - echo "Restoring dependencies..."
    - dotnet restore
    - echo "Building the project..."
    - dotnet build --configuration $CONFIGURATION --no-restore
  artifacts:
    paths:
      - bin/
      - obj/
  rules:
    - if: '$CI_MERGE_REQUEST_ID'