stages:
  - build
  - test

variables:
  DOTNET_VERSION: "8.0" 

build:
  stage: build
  
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/
      - obj/
  only:
    - merge_requests

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - dotnet test --no-restore --verbosity normal --configuration Release
  only:
    - merge_requests