stages:
  - build
  - test
  - prepare-version
  - build-image

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'


.build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Building Project..."
    - dotnet restore
    - dotnet build --no-restore
  artifacts:
    paths:
      - bin/
      - obj/

.test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  dependencies:
    - build
  script:
    - echo "Running tests..."
    - dotnet test 

preparing-version:
    stage: prepare-version
    image: ubuntu:22.04
    script:
      - apt-get update
      - apt-get install git -y
      - git config --global user.email "$GIT_EMAIL"
      - git config --global user.email "$GIT_USER"
      - git fetch --tags
      - git tag -l | tr -d v | sort -V | tail -n 1 > current_version.txt
    artifacts:
      paths:
        - current_version.txt

preparing-image:
  stage: build-image
  services:
    - docker:dind
  image: docker:latest
  script:
    - echo 'Build docker image for API deploy'
    - echo $CIS_CONTAINER_REGISTRY_URL
    - VERSION=$(cat current_version.txt)
    - docker login registry.gitlab.com -u $GITLAB_REGISTRY_USERNAME -p $GITLAB_REGISTRY_PASSWORD
    - docker build -t $CIS_CONTAINER_REGISTRY_URL:$VERSION .
    - docker tag -t $CIS_CONTAINER_REGISTRY_URL:$VERSION $CIS_CONTAINER_REGISTRY_URL:latest
    - docker push $CIS_CONTAINER_REGISTRY_URL:latest
