stages:
  - build
  - test

variables:
  DOTNET_VERSION: "8.0"
  CONFIGURATION: "Release"

before_script:
  - echo "Setting up .NET environment"
  - dotnet --version

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - echo "Compiling the code..."
    - dotnet restore
    - echo "Compile complete."
  artifacts:
    paths:
      - bin/
      - obj/
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  dependencies:
    - build
  script:
    - echo "Running tests..."
    - dotnet test --configuration $CONFIGURATION --no-build
  rules:
    - if: '$CI_MERGE_REQUEST_ID'