variables:
  EXE_RELEASE_FOLDER: 'cis-api-legacy-integration-phase-2/cis-api-legacy-integration-phase-2/bin/Release'
  TEST_FOLDER: 'cis-api-legacy-integration-phase-2/cis-api-legacy-integration-phase-2.Test/bin/Release'
  DOTNET_PATH: '/usr/bin/dotnet'

stages:
  - build
  - test

build_job:
  stage: build
  only:
    - tags
  script:
    - '$env:DOTNET_PATH restore'  
    - '$env:DOTNET_PATH build /p:Configuration=Release' 
  artifacts:
    expire_in: 1 week
    paths:
      - '$env:EXE_RELEASE_FOLDER/' 
test_job:
  stage: test
  only:
    - tags
  script:
    - '$env:DOTNET_PATH test $env:TEST_FOLDER/cis-api-legacy-integration-phase-2.Test.csproj --configuration Release'  
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - '$env:TEST_FOLDER/TestResults/' 
  dependencies:
    - build_job